id: jbossdemocentral-brms-install
title: JBoss BRMS easy install project to automate the installation of this product without preconfiguration beyond a single admin user.
github_repo_url: https://github.com/jbossdemocentral/brms-install-demo
technologies:
  - JBoss EAP
  - JBoss BRMS
summary: Project to automate the installation of this product without preconfiguration beyond a single admin user. There are three options available to you for using this demo; local, OpenShift and containerized.
level: Intermediate
product: brms
author: 
